export const SET_PLACE = 'SET_PLACE';

export const PLACE_CREATE_PENDING = 'PLACE_CREATE_PENDING';
export const PLACE_CREATE_SUCCESS = 'PLACE_CREATE_SUCCESS';
export const PLACE_CREATE_FAILURE = 'PLACE_CREATE_FAILURE';